spring:
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&userSSL=false
    username: root
    password: root
### mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    local-cache-scope: statement
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 设置实体类所对应的表的统一前缀
      table-prefix:
      # 设置统一的主键生成策略
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1
    banner: true
  # 配置类型别名所对应的包
  type-aliases-package: github.why168.entity
  # 扫描通用枚举的包
  type-enums-package: github.why168.enums
  mapper-locations: classpath*:/mapper/**/*.xml
